<?xml version="1.0" encoding="utf-8"?><Database Name="TaiKhoan" Class="QLTaiKhoanDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MYPC;Initial Catalog=TaiKhoan;Integrated Security=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="TaiKhoanConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TAIKHOAN" Member="TAIKHOANs">
    <Type Name="TAIKHOAN">
      <Column Name="TaiKhoan" Storage="_TaiKhoan1" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>